### PR TITLE
Fix hidden chapters, do not return hidden, fix #28

### LINKED ISSUE #28: NET translation has odd things in it
image
https://c.psmb.ru/#/date/2020-04-17/readings/%D0%A3%D1%82%D1%80%D0%B5%D0%BD%D1%8F

Every verse should take only one line and line breaks should be marked with <br/>.

image

### PR DESCRIPTION
**Pull request by brainstorm1313**
fix #28

### CODE REVIEW

File: bible.php [hunk 1]
```diff
@@ -323,12 +326,14 @@ public function run($zachalo = 'Притч. XV, 20 - XVI, 9.', $trans = null)
...
         $startPrintOptional = false;
+        $chapIdxsChapterRegular = false;
         if (trim($printChapterBegin) > trim($printChapterEnd)) {
             throw new Exception("printChapterBegin ($printChapterBegin) is bigger than printChapterEnd($printChapterEnd)");
         }
 
         for ($chapIdx = trim($printChapterBegin); $chapIdx <= $printChapterEnd; $chapIdx++) {
-            $chapIdxsChapterRegular = false;
+            if (!($chapIdxsChapterRegular && $startPrintRegular))
+                $chapIdxsChapterRegular = false;
```
Comment (dimaip) [inline bible.php]:
```suggestion
            if (!($chapIdxsChapterRegular && $startPrintRegular)) {
                $chapIdxsChapterRegular = false;
            }
```

File: bible.php [hunk 2]
```diff
@@ -416,9 +423,11 @@ public function run($zachalo = 'Притч. XV, 20 - XVI, 9.', $trans = null)
                 }
             }
 
-            $chapter['type'] = 'regular';
+            $chapter['type'] = $chapIdxsChapterRegular ? 'regular' : 'hidden';
+
 
-            $fragments[] = $chapter;
+            if($chapter['type'] !== 'hidden' || $this->returnHidden)
+                $fragments[] = $chapter;
```
Comment (dimaip) [inline bible.php]:
```suggestion
            if($chapter['type'] !== 'hidden' || $this->returnHidden) {
                $fragments[] = $chapter;
            }
```

**Review by dimaip — CHANGES_REQUESTED** [review]
Please fix the failing tests
